### ISSUE TITLE
Session Cookie?

### ISSUE THREAD

**Issue by ebounds** [smashwilson/slack-emojinator#2]
Can you leave the name of the session cookie? 

I've been trying the instructions over and over with all the data from different cookies put into the .env and then running the script, but I can't get it to work.

**Comment by smashwilson** [comment]
It's been a while, but I believe I just yanked the entire value of the "Cookie" header from Chrome's devtools.

**Comment by coltfred** [comment]
I can confirm that pasting the entire cookie inside of "" does work. It'd be nice if it were detailed in the README though.

**Comment by smashwilson** [comment]
:+1: Agreed. I'll leave this open to remind myself to do just that :grin:

**Comment by kvarga** [comment]
I updated the README slightly, does this help @coltfred ?

**Comment by kvarga** [comment]
Cleaned up, let me know if that helps.
