### ISSUE TITLE
Upload is not working.

### ISSUE THREAD

**Issue by JoaoLages** [smashwilson/slack-emojinator#20]
It's just what the title says. By following the instructions, I haven't been able to upload emojis.
Maybe it is my SLACK_COOKIE that is wrong. 
The document.cookie value is `b=.bwasdwerpu04gg8wcogkcg0kg`. I have tried with the quotes, without `b=`, without the dot, everything, but it doesn't work.
Can anyone help me out? Please post your working example, I should be missing something

**Comment by kvarga** [comment]
Haven't worked on this in a while, but the README seems wrong from what I remember (even though I was the one that added this section).

document.cookie doesn't return the Secure Cookies that is needed. Try skipping that step, it doesn't actually instruct you to use that value anywhere anyway. 

As long as that works for you, I'll open a Pull Request to remove that line from the Readme

**Comment by JoaoLages** [comment]
The emoji cookie is something required for the upload :/

**Comment by kvarga** [comment]
The steps after grab the cookies from the actual network request tab of the DevTools. 

document.cookie doesn't return the the necessary cookies because they are marked as Secure (only transmit over https:// and aren't available in Javascript).

**Comment by JoaoLages** [comment]
Oh ok.. I have 4 cookies in there, 1 is the output of `document.cookie`(it's the *b* cookie)
```
a-191264135237=Ci5Aagwcsgx8Hx7nqhoDxmC1rrpRhnyuAKVo2IaliBBlVdqRjC8qzIjB6ROMf6F7v6A1H54N3jgVs9sm%2BQL%2FyA%3D%3D; a=26218bqer31%2C191264135237; b=.ad5olus2bhko00s4o4gqfwte; a-262183777431=%2BObtFiYvquefa0DDJamNSH9HdCkUWGhhixtcthP%2BuBXUk6FPvLPMQDZ5oPYB8%2BelyYUSAgxI2dNjGeTSk%2FJz8w%3D%3D
```
I have tried all of them, what am I missing here?

**Comment by kvarga** [comment]
Did you add entire cookie string to SLACK_COOKIE line in the .env file? 

( https://github.com/smashwilson/slack-emojinator/blob/master/.env.example )

**Comment by JoaoLages** [comment]
Yup, I have tried adding the whole string too.

**Comment by JoaoLages** [comment]
Adding that whole string works after all, my bad! Thanks a lot!
