### ISSUE TITLE
Fails to upload; possible 302 redirect from slack?

### ISSUE THREAD

**Issue by cbowns** [smashwilson/slack-emojinator#3]
I've been plugging away at this for a bit and can't get it to work. I think I've got a proper cookie set up (via #2), but my uploads simply fail to go through. Looking at this traffic through Runscope vs an in-browser request with Chrome, it looks like Slack is returning a 302 to the main request the script makes.

If I toggle `allow_redirects` to `allow_redirects=True`, I get a `<Response [200]>` after `r.raise_for_status()`, but the upload itself is still not working. Any ideas on how to debug this further?

**Comment by gabeos** [comment]
same issue.. took same debug steps as @cbowns

**Comment by smashwilson** [comment]
Strange. I'm expecting that Slack just changed something about the way their web application behaves, and this script didn't follow. (It was a terrible, one-hour hack to begin with :wink:) Maybe there's additional verification on the request, now?

**Comment by austinemayer** [comment]
Have you made any progress on this issue?

**Comment by thatarchguy** [comment]
I'm seeing this same behaviour. Currently trying to upload all the pokemon emoji's :smile:

**Comment by supereli** [comment]
A 302 re-direct actually means the upload worked (strangley enough). They will return a 200 if it doesn't work. The likely problem is that the image doesn't fit their image standards (128x128 max pixels and 64K in size). I'm using a modified version of this script successfully still. I wrote some additional code to downsample images that exceed their maxsize before uploading. Working on integrating it a bit better with what's here and creating a pull request.

**Comment by kvarga** [comment]
I've put in a pull request ( #6 ) that will throw exception w/ Slack error (Most likely the 128x128 limit)

**Comment by kvarga** [comment]
The script should now give a clearer message if there is an error uploading an emoji. The issue is that Slack returns at 200 OK and then displays an error_alert box on the web page. I've resolved this by checking the page for the presence of the alert and throwing an exception, if necessary.

**Comment by HaloZero** [comment]
I'm still getting this issue. The page I'm getting redirected to is the login page. I'm wondering if the document.cookie part doesn't work. Have the latest master

**Comment by kvarga** [comment]
Nope, that definitely doesn't work. I tried it, but I must not have re-sourced the .env file. document.cookie can't get the https only cookies. Will fix documentation now.

**Comment by kvarga** [comment]
Cleaned up! #8
