### ISSUE TITLE
use slack API token instead of cookie

### ISSUE THREAD

**Issue by punkrockpolly** [smashwilson/slack-emojinator#4]

**Comment by smashwilson** [comment]
I would have preferred to, but as far as I can tell, the Slack API [doesn't expose an endpoint to add emoji](https://api.slack.com/methods). The upload script literally screenscrapes and submits the admin page form over and over. Unless I'm missing something?

Also, uh, this is less "maintained software" than "a terrible thing I hacked up in about an hour while on work travel," so fair warning, it's pretty far down on my list of stuff to fix :wink:

**Comment by punkrockpolly** [comment]
Lol no problem,  I got it working with the cookie to upload hundreds of emoji. Thanks for putting this together. Closing the issue.
